/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "BBBulletin.h"

@interface BBBulletin (SBUtilities)
- (id)sectionIconImageWithFormat:(int)arg1;
@end

