/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSMutableArray.h"

@interface NSMutableArray (SBArrayStackAdditions)
- (id)top;
- (id)popObject:(id)arg1;
- (id)pop;
- (void)push:(id)arg1;
@end

