/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSMutableSet.h"

@interface NSMutableSet (SBApplicationAdditions)
- (void)addObjectsFromDictionary:(id)arg1 forKeys:(id)arg2;
@end

