/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBAlertManagerDelegate <NSObject>
- (void)alertManager:(id)arg1 didDeactivateAlert:(id)arg2 overAlerts:(id)arg3;
- (void)alertManager:(id)arg1 willDeactivateAlert:(id)arg2 overAlerts:(id)arg3;
- (void)alertManager:(id)arg1 didActivateAlert:(id)arg2 overAlerts:(id)arg3;
- (void)alertManager:(id)arg1 willActivateAlert:(id)arg2 overAlerts:(id)arg3;
@end

