/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, SBAlertWindow;

@interface SBAlertManager : NSObject
{
    SBAlertWindow *_alertWindow;
    SBAlertWindow *_deferredAlertWindow;
    NSMutableArray *_alerts;
    BOOL _deactivatingAllAlerts;
    id <SBAlertManagerDelegate> _delegate;
}

@property(nonatomic) id <SBAlertManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_deactivateAfterNextLaunch:(id)arg1;
- (void)_updateSEOStatus;
- (void)_tearDownAlertWindow:(id)arg1;
- (id)debugDescription;
- (id)description;
- (void)removeFromView:(id)arg1;
- (void)_updateStatusBarTimeItemEnabled;
- (int)_interfaceOrientationForActivation;
- (struct CGRect)_alertWindowRect;
- (int)orientation;
- (void)noteOrientationChanged:(int)arg1;
- (void)workspaceDidAnimateSuspendingApp;
- (void)workspaceWillAnimateActivatingApp;
- (void)deactivateAlertsAfterLaunch;
- (void)setAlertsShouldDeactivateAfterLaunch;
- (void)deactivateAll;
- (BOOL)containsAlert:(id)arg1;
- (void)_deactivate:(id)arg1;
- (void)deactivate:(id)arg1;
- (void)_activate:(id)arg1;
- (void)activate:(id)arg1;
- (id)allAlerts;
- (BOOL)hasStackedAlerts;
- (id)activeAlert;
- (id)window;
- (void)dealloc;
- (id)init;

@end

