/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSOperation.h"

@class NSSet;

@interface SBApplicationDataLookupOperation : NSOperation
{
    NSSet *_registeredBundleIDs;
    NSSet *_unregisteredBundleIDs;
}

- (void)main;
- (void)dealloc;
- (id)initWithRegisteredBundleIDs:(id)arg1 unregisteredBundleIDs:(id)arg2;

@end

