/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBAppSwitcherBarViewDelegate <NSObject>
- (void)appSwitcherBar:(id)arg1 pageAtIndexDidDisappear:(int)arg2;
- (void)appSwitcherBar:(id)arg1 pageAtIndexDidAppear:(int)arg2;
- (BOOL)appSwitcherBar:(id)arg1 scrollShouldCancelInContentForView:(id)arg2;
- (void)appSwitcherBarRemovedFromSuperview:(id)arg1;
@end

