/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBNewsstandItemIconViewBase.h"

@interface SBAppSwitcherNewsstandItemIconView : SBNewsstandItemIconViewBase
{
}

+ (Class)_labelImageParametersClassForIcon:(id)arg1 location:(int)arg2;
+ (struct CGPoint)_badgeSashCenterPoint;
+ (float)_badgeLabelFontSize;
+ (float)_badgeSashWidth;
+ (struct UIEdgeInsets)_badgeSashInsets;
+ (id)_badgeBaseImage;
+ (BOOL)_hasBadgeLabel;
- (id)_superviewForAccessoryView;
- (float)_badgeHorizontalPadding;
- (void)positionIconImageView;
- (void)positionCloseBoxOfType:(int)arg1;
- (void)_updateLabelVisibility;
- (void)setShadowsHidden:(BOOL)arg1;
- (struct CGRect)defaultFrameForProgressBar;
- (id)initWithFrame:(struct CGRect)arg1;

@end

