/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBBannerDismissOverdueContext : NSObject
{
    int _dismissReason;
}

+ (id)dismissOverdueContextWithReason:(int)arg1;
@property(nonatomic) int dismissReason; // @synthesize dismissReason=_dismissReason;

@end

