/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBBulletinWindowClient <NSObject>
- (void)bulletinWindowDidRotateFromOrientation:(int)arg1;
- (void)bulletinWindowIsAnimatingRotationToOrientation:(int)arg1;
- (void)bulletinWindowWillRotateToOrientation:(int)arg1;

@optional
- (BOOL)requiresKeyWindow;
@end

