/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBBulletinCellContentViewBase.h"

@class UIView;

@interface SBBulletinCellContentView : SBBulletinCellContentViewBase
{
    UIView *_blurView;
    UIView *_contentView;
    BOOL _italicizeContent;
    float _shadowBlur;
    void *_data;
    unsigned long _dataLength;
    BOOL _buttonsBelowContent;
}

+ (float)heightForSystemAlertStyleWithTitle:(id)arg1 maxLines:(unsigned int)arg2 message:(id)arg3 maxLines:(unsigned int)arg4 contentWidth:(float)arg5;
+ (float)heightForBulletinStyleWithSubtitle:(id)arg1 imageHeight:(float)arg2 italicize:(BOOL)arg3;
+ (float)heightForBulletinStyleWithSubtitle:(id)arg1 message:(id)arg2 maxLines:(unsigned int)arg3 contentWidth:(float)arg4 italicize:(BOOL)arg5;
+ (id)_attachmentFont:(BOOL)arg1;
+ (id)_messageFont:(BOOL)arg1;
+ (id)_subtitleFont:(BOOL)arg1;
+ (id)_dateFont:(BOOL)arg1;
+ (id)_titleFont:(BOOL)arg1;
- (void)displayLayer:(id)arg1;
- (void)drawInGrayscaleContexts;
- (void)drawInColorContext;
- (BOOL)getSourceData:(struct vImage_Buffer *)arg1 dstData:(struct vImage_Buffer *)arg2;
- (void)setNeedsDisplay;
- (void)setShadowColor:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)_drawLabel:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)layoutSubviews;
- (void)_layoutAttachmentTextAtX:(float)arg1;
- (float)_layoutMessageAtX:(float)arg1 y:(float)arg2;
- (float)_layoutAttachmentImageAtX:(float)arg1 y:(float)arg2;
- (float)_layoutSubtitleAtX:(float)arg1 y:(float)arg2;
- (float)_layoutTitleAtX:(float)arg1 y:(float)arg2;
- (BOOL)_shouldVerticallyCenterBulletinStyleTitleAndDate;
- (id)_attachmentFont;
- (id)_messageFont;
- (id)_subtitleFont;
- (id)_titleFont;
- (id)_dateFont;
- (void)_configureLabel:(id)arg1 withFont:(id)arg2 alignment:(int)arg3;
- (void)dealloc;
- (id)_initForLayoutStyle:(int)arg1;
- (void)setHasButtonBelow:(BOOL)arg1;
- (void)setShadowBlur:(float)arg1;
- (void)setItalicizesContent:(BOOL)arg1;

@end

