/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class CALayer;

@interface SBBuddyLogoZoomView : UIView
{
    CALayer *_contentLayer;
    id _animationCompleteBlock;
}

- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)startAnimationWithCompletionBlock:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

