/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface SBBulletinDateLabelFactory : NSObject
{
    NSMutableDictionary *_recycledLabelsByStyle;
}

+ (id)sharedInstance;
- (void)_purgeRecycledLabels;
- (int)_styleForLabel:(id)arg1;
- (void)recycleLabel:(id)arg1;
- (id)labelWithStartDate:(id)arg1 endDate:(id)arg2 timeZone:(id)arg3 allDay:(BOOL)arg4 forStyle:(int)arg5;
- (void)dealloc;
- (id)init;

@end

