/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBBulletinDateLabel <NSObject>
@property(nonatomic) id <SBDateLabelDelegate> delegate;
@property(nonatomic, getter=isAllDay) BOOL allDay;
- (void)prepareForReuse;
- (void)stopCoalescingUpdates;
- (void)startCoalescingUpdates;
- (void)setEndDate:(id)arg1 withTimeZone:(id)arg2;
- (void)setStartDate:(id)arg1 withTimeZone:(id)arg2;
@end

