/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIGestureRecognizer.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@interface SBBulletinListTouchEater : UIGestureRecognizer <UIGestureRecognizerDelegate>
{
}

- (BOOL)canBePreventedByGestureRecognizer:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;

@end

