/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBCallFailureAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)bottomBarForInstance:(id)arg1;
+ (id)topBarForInstance:(id)arg1;
- (void)setAlert:(id)arg1;
- (void)callBack:(id)arg1;
- (void)ignore:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

