/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSOperation.h"

@class NSMutableArray;

@interface SBCancelableBlockOperation : NSOperation
{
    NSMutableArray *_blocks;
}

- (void)main;
- (void)dealloc;
- (void)addBlock:(id)arg1;
- (id)init;

@end

