/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface SBCornerViewFactory : NSObject
{
}

+ (id)newCornerWindowForCorner:(int)arg1 windowLevel:(float)arg2 cornersFrame:(struct CGRect)arg3;
+ (id)newCornerViewForCorner:(int)arg1 cornersFrame:(struct CGRect)arg2;

@end

