/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDateFormatter, NSNumberFormatter;

@interface SBDateLabelStringFormatCache : NSObject
{
    NSDateFormatter *_dayOfWeekFormatter;
    NSDateFormatter *_dayMonthYearFormatter;
    NSDateFormatter *_dayMonthFormatter;
    NSDateFormatter *_timeFormatter;
    NSNumberFormatter *_decimalFormatter;
}

+ (id)sharedInstance;
+ (void)load;
- (id)formatDateAsTimeStyle:(id)arg1;
- (id)formatDateAsDayMonthStyle:(id)arg1;
- (id)formatDateAsDayMonthYearStyle:(id)arg1;
- (id)formatDateAsDayOfWeek:(id)arg1;
- (id)formatNumberAsDecimal:(id)arg1;
- (void)resetFormatters:(id)arg1;
- (void)resetFormattersIfNecessary;
- (void)dealloc;
- (id)init;

@end

