/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBDeviceLockPasscodeEntryAlert : SBAlert
{
}

+ (id)sharedInstance;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (int)statusBarStyle;
- (void)deactivate;

@end

