/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UILabel.h"

#import "SBBulletinDateLabel-Protocol.h"

@class NSDate;

@interface SBDefaultDateLabel : UILabel <SBBulletinDateLabel>
{
    NSDate *_timeZoneRelativeStartDate;
    NSDate *_timeZoneRelativeEndDate;
    BOOL _allDay;
    NSDate *_effectiveAllDayStartDate;
    NSDate *_effectiveAllDayLastValidDate;
    NSDate *_effectiveAllDayEndDate;
    BOOL _effectiveAllDay;
    BOOL _isCoalescingUpdates;
    BOOL _needsUpdateFromCoalesce;
    id <SBDateLabelDelegate> _delegate;
}

+ (id)_currentCalendar;
@property(nonatomic) id <SBDateLabelDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isAllDay) BOOL allDay; // @synthesize allDay=_allDay;
- (void)stopCoalescingUpdates;
- (void)startCoalescingUpdates;
- (void)update;
- (void)_forceUpdate;
- (void)updateTextIfNecessary;
- (void)updateTextIfNecessary:(BOOL)arg1;
- (id)constructLabelString;
- (BOOL)isEffectiveAllDay;
- (BOOL)isDateWithinEffectiveAllDayRange:(id)arg1;
- (id)_localDateForDate:(id)arg1 inTimeZone:(id)arg2;
- (void)_updateEffectiveAllDayTimes;
- (void)_resetEffectiveAllDayState:(BOOL)arg1;
- (void)setEndDate:(id)arg1 withTimeZone:(id)arg2;
- (void)setStartDate:(id)arg1 withTimeZone:(id)arg2;
- (void)setTimeZoneRelativeEndDate:(id)arg1;
- (void)setTimeZoneRelativeStartDate:(id)arg1 absoluteStartDate:(id)arg2;
- (void)prepareForReuse;
- (void)dealloc;
- (id)init;

@end

