/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIImageView.h"

@class UIView;

@interface SBDownloadingProgressBar : UIImageView
{
    UIView *_clipView;
    UIImageView *_fillView;
    float _progress;
}

+ (float)defaultHeight;
- (void)updateFill;
- (float)progress;
- (void)setProgress:(float)arg1;
- (id)fillImage;
- (id)trackImage;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

