/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIconObserver-Protocol.h"

@protocol SBFolderIconObserver <SBIconObserver>
- (void)folderIcon:(id)arg1 didUpdateGridImage:(id)arg2 withSkipping:(BOOL)arg3 forContainedIconImageUpdate:(id)arg4;
@end

