/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIconListView.h"

@interface SBFolderIconListView : SBIconListView
{
}

+ (unsigned int)iconRowsForInterfaceOrientation:(int)arg1;
+ (unsigned int)iconColumnsForInterfaceOrientation:(int)arg1;
- (struct CGRect)nineIconRectForScrollPosition:(int)arg1;
- (float)bottomIconInset;
- (float)topIconInset;

@end

