/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBFolderNotchView.h"

@interface SBLinenNotchView : SBFolderNotchView
{
}

+ (id)_squareImageForNotchInfo:(CDStruct_d18cc6b1)arg1 orientation:(int)arg2;

@end

