/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIconRotationContainer.h"

@interface SBNewsstandIconRotationContainer : SBIconRotationContainer
{
}

- (void)crossfadeWithDuration:(double)arg1 inIconList:(id)arg2;
- (void)setStartIcon:(id)arg1 endIcon:(id)arg2 inIconList:(id)arg3 fromOrientation:(int)arg4 toOrientation:(int)arg5;

@end

