/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBFolderScrollOffset.h"

@interface SBNewsstandFolderScrollOffset : SBFolderScrollOffset
{
    unsigned int _firstVisibleRow;
}

@property unsigned int firstVisibleRow; // @synthesize firstVisibleRow=_firstVisibleRow;

@end

