/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIconGridImage.h"

@interface SBNewsstandIconGridImage : SBIconGridImage
{
}

+ (struct CGRect)rectAtIndex:(unsigned int)arg1 forImage:(id)arg2 maxCount:(unsigned int)arg3;
+ (struct CGSize)cellSpacing;
+ (struct CGSize)cellSize;

@end

