/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBIconListModel.h"

@interface SBNewsstandIconListModel : SBIconListModel
{
}

+ (Class)viewClass;
- (unsigned int)firstFreeSlotIndexForType:(int)arg1;
- (BOOL)allowsAddingIcon:(id)arg1;

@end

