/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBNewsstandItemIconViewBase.h"

@class UILabel, UIView;

@interface SBNewsstandItemIconView : SBNewsstandItemIconViewBase
{
    UIView *_iconTransformView;
    UILabel *_indexLabel;
    unsigned int _newsstandIndex;
}

+ (struct CGPoint)_badgeSashCenterPoint;
+ (float)_badgeLabelFontSize;
+ (float)_badgeSashWidth;
+ (struct UIEdgeInsets)_badgeSashInsets;
+ (id)_badgeBaseImage;
+ (struct CGSize)_maxLabelSize;
+ (struct CGSize)defaultIconSize;
- (void)setNewsstandIndex:(unsigned int)arg1;
- (struct CGRect)_adjustProspectiveBadgeFrame:(struct CGRect)arg1 fromView:(id)arg2 toView:(id)arg3;
- (void)positionLabel;
- (void)setIsGrabbed:(BOOL)arg1;
- (void)positionIconImageView;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)applyIconImageTransform:(struct CATransform3D)arg1 duration:(float)arg2 delay:(float)arg3;
- (id)createShadowImageView;
- (void)positionCloseBoxOfType:(int)arg1;
- (void)prepareForRecycling;
- (struct CGRect)defaultFrameForProgressBar;
- (void)dealloc;
- (id)initWithDefaultSize;
- (id)initWithFrame:(struct CGRect)arg1;

@end

