/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlertView.h"

@class NSTimer, SBPowerDownController, TPBottomSingleButtonBar, TPTopLockBar, UIView;

@interface SBPowerDownView : SBAlertView
{
    UIView *_dimView;
    TPTopLockBar *_lockView;
    TPBottomSingleButtonBar *_cancelView;
    SBPowerDownController *_powerDownController;
    NSTimer *_autoDismissTimer;
}

- (void)layoutForInterfaceOrientation:(int)arg1;
- (BOOL)isSupportedInterfaceOrientation:(int)arg1;
- (void)animateDark;
- (void)animateOut;
- (void)animateIn;
- (void)notifyDelegateOfPowerDown;
- (void)finishedAnimatingOut;
- (void)finishedAnimatingIn;
- (void)setPowerDownController:(id)arg1;
- (void)powerDown:(id)arg1;
- (void)lockBarStoppedTracking:(id)arg1;
- (void)lockBarStartedTracking:(id)arg1;
- (void)lockBarUnlocked:(id)arg1;
- (void)cancel:(id)arg1;
- (void)resetAutoDismissTimer;
- (void)cancelAutoDismissTimer;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

