/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBWorkspaceTransaction.h"

@class SBApplication, SBAwayController;

@interface SBReturnToLockscreenWorkspaceTransaction : SBWorkspaceTransaction
{
    SBApplication *_fromApp;
    SBAwayController *_awayController;
}

- (BOOL)selfApplicationDidBecomeReceiver:(id)arg1 fromApplication:(id)arg2;
- (BOOL)selfWorkspaceDidResume;
- (BOOL)selfAlertDidActivate:(id)arg1 overAlerts:(id)arg2;
- (void)_commit;
- (void)dealloc;
- (id)initWithWorkspace:(id)arg1 alertManager:(id)arg2 fromApplication:(id)arg3 toAwayController:(id)arg4;

@end

