/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class UIBezierPath, UIColor;

@interface SBResetProgressView : UIView
{
    UIColor *_progressColor;
    UIBezierPath *_path;
    float _resetProgress;
}

- (void)drawRect:(struct CGRect)arg1;
- (id)_progressColor;
- (id)_outlinePath;
- (void)setResetProgress:(float)arg1;
- (void)dealloc;

@end

