/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SPSearchAgent.h"

#import "SPDaemonQueryDelegate-Protocol.h"

@class NSDate, NSMutableDictionary, NSTimer;

@interface SBSearchModel : SPSearchAgent <SPDaemonQueryDelegate>
{
    NSTimer *_clearSearchTimer;
    NSDate *_clearSearchDate;
    NSMutableDictionary *_cachedImages;
}

+ (id)sharedInstance;
- (id)_customImageForPath:(id)arg1;
- (id)imageForDisplayIdentifier:(id)arg1 spotlightKey:(id)arg2;
- (id)imageViewForDomain:(unsigned int)arg1 andDisplayID:(id)arg2;
- (id)_imageForDomain:(unsigned int)arg1 andDisplayID:(id)arg2;
- (void)handleOptionsForNewSections:(id)arg1;
- (void)clear;
- (id)launchingURLForResult:(id)arg1 withDisplayIdentifier:(id)arg2 andSection:(id)arg3;
- (void)_updateClearSearchTimerFireDate;
- (void)startClearSearchTimer;
- (void)_clearSearchTimerFired;
- (void)resetClearSearchTimer;
- (void)dealloc;
- (id)init;

@end

