/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBSIMLockEntryAlert : SBAlert
{
    int _status;
}

- (void)deactivate;
- (void)activate;
- (int)status;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (id)init;

@end

