/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class AVController, NSHashTable, NSMutableDictionary, SBUISound;

@interface SBSoundController : NSObject
{
    NSMutableDictionary *_soundsBySystemSoundIDs;
    AVController *_ringtoneController;
    id _ringtoneObserver;
    SBUISound *_ringtoneSound;
    NSHashTable *_observers;
}

+ (id)sharedInstance;
- (void)_soundDidFinishPlaying:(id)arg1;
- (void)_soundDidStartPlaying:(id)arg1;
- (void)_ringerStateChanged:(id)arg1;
- (BOOL)_playRingtone:(id)arg1;
- (BOOL)_playSystemSound:(id)arg1;
- (void)_killRingtone;
- (void)_killSystemSound:(unsigned long)arg1;
- (void)_cleanupSystemSound:(unsigned long)arg1 andKill:(BOOL)arg2;
- (BOOL)handleVolumeButtonDownEvent;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)stopAllSounds;
- (void)stopSound:(id)arg1;
- (BOOL)playSound:(id)arg1 completion:(id)arg2;
- (BOOL)playSound:(id)arg1;
- (BOOL)isPlaying:(id)arg1;
- (BOOL)isPlayingAnySound;
- (void)dealloc;
- (id)init;

@end

