/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIAlertView.h"

@interface SBSystemLocalNotificationAlertSheet : UIAlertView
{
    BOOL _lockToPortrait;
}

- (BOOL)requiresPortraitOrientation;
- (void)setLockToPortrait:(BOOL)arg1;

@end

