/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBWorkspaceTransaction.h"

@class SBApplication;

@interface SBToAppWorkspaceTransaction : SBWorkspaceTransaction
{
    SBApplication *_toApp;
    BOOL _activateSuspended;
    double _watchdogExtension;
    BOOL _fromAssistant;
    SBApplication *_toApplication;
}

@property(retain, nonatomic) SBApplication *toApplication; // @synthesize toApplication=_toApplication;
- (void)_captureApplicationData:(id)arg1;
- (BOOL)_shouldBeWatchdogged:(id *)arg1;
- (double)_watchdogInterval;
- (void)_transactionComplete;
- (void)toggleStatusBarForCleanup;
- (void)performToAppStateCleanup;
- (BOOL)shouldPerformToAppStateCleanupOnCompletion;
- (BOOL)shouldToggleSpringBoardStatusBarOnCleanup;
- (BOOL)shouldHideSpringBoardStatusBarOnCleanup;
- (void)dealloc;
- (id)initWithWorkspace:(id)arg1 alertManager:(id)arg2 toApplication:(id)arg3;

@end

