/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

@interface SBTTYPromptAlertDisplay : SBSlidingAlertDisplay
{
}

+ (id)bottomBarForInstance:(id)arg1;
+ (id)topBarForInstance:(id)arg1;
- (void)_ignore:(id)arg1;
- (void)_chooseTTYMode:(id)arg1;
- (void)_chooseVoiceMode:(id)arg1;
- (void)_makeCall;
- (id)initWithSize:(struct CGSize)arg1;

@end

