/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBAlert.h"

@class SBAlertView, SBUIFullscreenAlertController;

@interface SBUIFullscreenAlertAdapter : SBAlert
{
    SBUIFullscreenAlertController *_alertController;
    SBAlertView *_alertDisplay;
}

- (id)description;
- (void)launchSucceeded:(BOOL)arg1;
- (void)handleAutoLock;
- (BOOL)handleHeadsetButtonPressed:(BOOL)arg1;
- (BOOL)handleVolumeDownButtonPressed;
- (BOOL)handleVolumeUpButtonPressed;
- (BOOL)handleLockButtonPressed;
- (BOOL)handleMenuButtonTap;
- (void)alertWindow:(id)arg1 didRotateFromInterfaceOrientation:(int)arg2;
- (void)alertWindow:(id)arg1 willAnimateRotationToInterfaceOrientation:(int)arg2 duration:(double)arg3;
- (void)alertWindow:(id)arg1 willRotateToInterfaceOrientation:(int)arg2 duration:(double)arg3;
- (void)alertWindow:(id)arg1 resizedFromContentFrame:(struct CGRect)arg2 toContentFrame:(struct CGRect)arg3;
- (id)alertController;
- (void)_pluginViewAnimatedOut:(id)arg1;
- (void)animateViewOut;
- (void)prepareViewToAnimateOut;
- (void)setViewShouldAnimateIn:(BOOL)arg1;
- (BOOL)viewDisplaysAboveStatusBar;
- (BOOL)viewIsReadyToBeRemoved;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (void)deactivate;
- (void)dealloc;
- (BOOL)allowsStackingOfAlert:(id)arg1;
- (BOOL)hasTranslucentBackground;
- (BOOL)allowsEventOnlySuspension;
- (id)initWithAlertController:(id)arg1;

@end

