/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBUIAnimationControllerDelegate <NSObject>
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)animationController:(id)arg1 didCommitAnimation:(BOOL)arg2 withDuration:(double)arg3 afterDelay:(double)arg4;
- (void)animationController:(id)arg1 willBeginAnimation:(BOOL)arg2;
@end

