/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBApplicationIcon.h"

@interface SBUserInstalledApplicationIcon : SBApplicationIcon
{
    BOOL _shouldHaveSash;
}

- (int)accessoryTypeForLocation:(int)arg1;
- (void)_checkHasBeenLaunchedState;
- (BOOL)_shouldShowSashForNewlyInstalledApp;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;
- (id)uninstallAlertTitle;
- (id)ratingsAlertRateButtonTitle;
- (id)ratingsAlertSkipTitle;
- (id)ratingsAlertBody;
- (id)ratingsAlertTitle;
- (BOOL)hasBeenSyncedBackToITunes;
- (BOOL)allowsUninstall;
- (id)initWithApplication:(id)arg1;

@end

