/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SBWorkspaceTransactionDelegate <NSObject>
- (void)transactionDidFinish:(id)arg1 success:(BOOL)arg2;
@end

