/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray;

@interface SBZoomView : UIView
{
    BOOL _hasImage;
    BOOL _hasFullSizedImage;
    int _corners;
    NSMutableArray *_cornerViews;
}

- (id)_chromeStatusBarImageForInterfaceOrientation:(int)arg1;
- (void)setRoundedCorners:(int)arg1 withCornersFrame:(struct CGRect)arg2;
- (struct CGSize)_rotateAndNormalizeSize:(struct CGSize)arg1 withTransform:(struct CGAffineTransform)arg2;
- (int)_degreesForRotationFromOriginalImageOrientation:(int)arg1 toInterfaceOrientation:(int)arg2;
- (int)_degreesForRotationFromInterfaceOrientation:(int)arg1 toInterfaceOrientation:(int)arg2;
- (void)dealloc;
- (id)initWithView:(id)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithSnapshotFrame:(struct CGRect)arg1 ioSurface:(void *)arg2 snapshotTransform:(struct CGAffineTransform)arg3;
- (id)initWithSnapshotFrame:(struct CGRect)arg1 image:(id)arg2 originalImageOrientation:(int)arg3 currentImageOrientation:(int)arg4 interfaceOrientation:(int)arg5 doubleHeightStatusBar:(BOOL)arg6 preventSplit:(BOOL)arg7 chrome:(id)arg8 chromeStatusBarHidden:(BOOL)arg9 needsZoomFilter:(BOOL)arg10 asyncDecodeImage:(BOOL)arg11;
- (id)initWithFrame:(struct CGRect)arg1;

@end

