/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SBManualKeyboardTextField.h"

@interface WhiteBorderedTextField : SBManualKeyboardTextField
{
}

- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)textRect;
- (void)drawBorder:(struct CGRect)arg1;

@end

